{"b222bd8481e1767451379d634e26e4a9":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"5e4b37af3de45c20","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/5e4b37af3de45c20","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa912ecc550>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199985601,"stop":1673199985601,"duration":0}},{"uid":"ee35b6a7ebb755bc","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/ee35b6a7ebb755bc","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb399b5c2d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190992630,"stop":1673190992630,"duration":0}},{"uid":"6832058a12dd6aa2","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/6832058a12dd6aa2","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a13152110>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189383369,"stop":1673189383369,"duration":0}},{"uid":"e5324c8f36e5adb9","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/e5324c8f36e5adb9","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbac4d0810>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187013674,"stop":1673187013674,"duration":0}}]},"be922e884fc0b322078bbd91d644a646":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"4aedfa01da912de7","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/4aedfa01da912de7","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa91369ca10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199984197,"stop":1673199984197,"duration":0}},{"uid":"ebfcdbec638a1659","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/ebfcdbec638a1659","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb39a38cf50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190991269,"stop":1673190991269,"duration":0}},{"uid":"1981479f9dc8d37c","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/1981479f9dc8d37c","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a1347cc50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189382023,"stop":1673189382023,"duration":0}},{"uid":"4fbbba3aee6744c2","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/4fbbba3aee6744c2","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbab519650>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187012182,"stop":1673187012182,"duration":0}}]},"5dea5b55e991fa0d651d962c092e5bfe":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"c0f09a00c9f26f39","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/c0f09a00c9f26f39","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa91369ca10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199983431,"stop":1673199983431,"duration":0}},{"uid":"6477be7e6493e841","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/6477be7e6493e841","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb39a38cf50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190990527,"stop":1673190990527,"duration":0}},{"uid":"6f8efb881a4d96eb","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/6f8efb881a4d96eb","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a1347cc50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189381288,"stop":1673189381288,"duration":0}},{"uid":"f421f8135cf66dd","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/f421f8135cf66dd","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbab519650>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187011380,"stop":1673187011380,"duration":0}}]},"500b88c9e2c30d874c1710f6f6873043":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"2b73c241d12addc1","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/2b73c241d12addc1","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa912ecc550>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199986055,"stop":1673199986055,"duration":0}},{"uid":"ef450058a5bf62e2","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/ef450058a5bf62e2","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb399b5c2d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190993071,"stop":1673190993071,"duration":0}},{"uid":"cb74164d17f1e0b0","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/cb74164d17f1e0b0","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a13152110>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189383811,"stop":1673189383811,"duration":0}},{"uid":"7d58d0c818fa8b14","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/7d58d0c818fa8b14","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbac4d0810>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187014163,"stop":1673187014163,"duration":0}}]},"69b2cce925f59635003662b7b0f2ff21":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"17a240b68203d16f","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/17a240b68203d16f","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa91369ca10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199984052,"stop":1673199984052,"duration":0}},{"uid":"7aeb42ba3c759e17","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/7aeb42ba3c759e17","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb39a38cf50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190991128,"stop":1673190991128,"duration":0}},{"uid":"52d92c821f67500d","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/52d92c821f67500d","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a1347cc50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189381882,"stop":1673189381882,"duration":0}},{"uid":"9475d74df63bb652","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/9475d74df63bb652","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbab519650>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187012033,"stop":1673187012033,"duration":0}}]},"d8756eef83cee8a5f4dc8be4432511a3":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"8012c03b4c5ccd54","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/8012c03b4c5ccd54","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa91369ca10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199982197,"stop":1673199982197,"duration":0}},{"uid":"4935fb6692dd608","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/4935fb6692dd608","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb39a38cf50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190989346,"stop":1673190989346,"duration":0}},{"uid":"4862fcf40aaa8ca0","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/4862fcf40aaa8ca0","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a1347cc50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189380124,"stop":1673189380124,"duration":0}},{"uid":"92c65cbbed12b9a9","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/92c65cbbed12b9a9","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbab519650>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187010117,"stop":1673187010117,"duration":0}}]},"21a18d122fcae940f88903e0b0d8d7c7":{"statistic":{"failed":3,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":4},"items":[{"uid":"815c7ee2b221f852","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/815c7ee2b221f852","status":"passed","time":{"start":1673199981085,"stop":1673199981086,"duration":1}},{"uid":"2cc4b0a34301b40a","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/2cc4b0a34301b40a","status":"failed","statusDetails":"AssertionError: assert 400 == 200\n +  where 400 = <Response [400]>.status_code","time":{"start":1673190988061,"stop":1673190988284,"duration":223}},{"uid":"24ae7f2316b833c9","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/24ae7f2316b833c9","status":"failed","statusDetails":"AssertionError: assert 400 == 200\n +  where 400 = <Response [400]>.status_code","time":{"start":1673189378822,"stop":1673189378997,"duration":175}},{"uid":"e9d79eb1871c2e4a","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/e9d79eb1871c2e4a","status":"failed","statusDetails":"AssertionError: assert 400 == 200\n +  where 400 = <Response [400]>.status_code","time":{"start":1673187008650,"stop":1673187008956,"duration":306}}]},"11bf864f01a5895b5f5d4e0b8d2e9d88":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"c3011d52aa85186b","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/c3011d52aa85186b","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa912e62150>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199987818,"stop":1673199987818,"duration":0}},{"uid":"8707bc1266225e16","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/8707bc1266225e16","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb399c16290>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190994749,"stop":1673190994749,"duration":0}},{"uid":"637135bf102f93ff","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/637135bf102f93ff","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a12c4be90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189385483,"stop":1673189385483,"duration":0}},{"uid":"2e94280b6aaaa8de","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/2e94280b6aaaa8de","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbaad260d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187015969,"stop":1673187015969,"duration":0}}]},"d8bc09f397575c83c8084a3920ba3d77":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"470bca437800baea","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/470bca437800baea","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa91369ca10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199982509,"stop":1673199982509,"duration":0}},{"uid":"9abd2514a6944e1","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/9abd2514a6944e1","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb39a38cf50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190989646,"stop":1673190989646,"duration":0}},{"uid":"3cdc5495f53590b0","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/3cdc5495f53590b0","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a1347cc50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189380423,"stop":1673189380423,"duration":0}},{"uid":"150a3871146f712f","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/150a3871146f712f","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbab519650>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187010441,"stop":1673187010441,"duration":0}}]},"491976313902a9d9a530daa5df2a6c71":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"a9d7b5dcfc7abc6f","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/a9d7b5dcfc7abc6f","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa91369ca10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199982655,"stop":1673199982655,"duration":0}},{"uid":"e4d0f8dbac0e3164","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/e4d0f8dbac0e3164","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb39a38cf50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190989788,"stop":1673190989788,"duration":0}},{"uid":"df0beb509b426bbc","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/df0beb509b426bbc","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a1347cc50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189380562,"stop":1673189380562,"duration":0}},{"uid":"3fd776827c810480","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/3fd776827c810480","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbab519650>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187010587,"stop":1673187010587,"duration":0}}]},"595a8145431fa6b432b01286142b3ff0":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"79ceed1e0fc5c4d3","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/79ceed1e0fc5c4d3","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa91369ca10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199984504,"stop":1673199984504,"duration":0}},{"uid":"6ead3cea75ba336","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/6ead3cea75ba336","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb39a38cf50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190991570,"stop":1673190991570,"duration":0}},{"uid":"c36b243ca26c356e","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/c36b243ca26c356e","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a1347cc50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189382320,"stop":1673189382320,"duration":0}},{"uid":"96f34f38d32a25eb","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/96f34f38d32a25eb","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbab519650>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187012509,"stop":1673187012509,"duration":0}}]},"d55ee81a3514f5c2febb5efd4a205826":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"6b103115ecfad0ee","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/6b103115ecfad0ee","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa912ecc550>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199985910,"stop":1673199985910,"duration":0}},{"uid":"8eef6184b1791a0c","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/8eef6184b1791a0c","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb399b5c2d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190992929,"stop":1673190992929,"duration":0}},{"uid":"dd3937938f3b28db","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/dd3937938f3b28db","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a13152110>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189383668,"stop":1673189383668,"duration":0}},{"uid":"f0d266117c90a2b5","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/f0d266117c90a2b5","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbac4d0810>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187014013,"stop":1673187014013,"duration":0}}]},"177bf47ad71d2c6a373169d721b4a8dc":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"2afbe2f703186a8f","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/2afbe2f703186a8f","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa912ecc550>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199984981,"stop":1673199984981,"duration":0}},{"uid":"af56236e75650670","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/af56236e75650670","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb399b5c2d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190992022,"stop":1673190992022,"duration":0}},{"uid":"30d6383261128d71","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/30d6383261128d71","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a13152110>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189382770,"stop":1673189382770,"duration":0}},{"uid":"16e0978285abc0d6","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/16e0978285abc0d6","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbac4d0810>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187013003,"stop":1673187013003,"duration":0}}]},"60d6b94a3ae57a737e98d0b797974837":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"7f33625c86d6f03d","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/7f33625c86d6f03d","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa91369ca10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199983594,"stop":1673199983594,"duration":0}},{"uid":"c8c42dde5ecd0689","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/c8c42dde5ecd0689","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb39a38cf50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190990684,"stop":1673190990684,"duration":0}},{"uid":"55d2f73addf20b41","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/55d2f73addf20b41","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a1347cc50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189381444,"stop":1673189381444,"duration":0}},{"uid":"f4828996b50f50ed","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/f4828996b50f50ed","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbab519650>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187011554,"stop":1673187011554,"duration":0}}]},"af6a36f8aa85b2ef3c5fdd57f3801ce8":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"2130ddab1dc720d3","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/2130ddab1dc720d3","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa9132a4c50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199987181,"stop":1673199987181,"duration":0}},{"uid":"5ecc9f1549515ad0","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/5ecc9f1549515ad0","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb399d5ed90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190994141,"stop":1673190994141,"duration":0}},{"uid":"e0a69adfdb9df0d0","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/e0a69adfdb9df0d0","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a12c080d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189384877,"stop":1673189384877,"duration":0}},{"uid":"e37034db1ab246b1","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/e37034db1ab246b1","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbab37e450>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187015322,"stop":1673187015322,"duration":0}}]},"04e955e8efdddecde906f33889350980":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"5d10ee26653e03b3","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/5d10ee26653e03b3","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa912d752d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199987667,"stop":1673199987667,"duration":0}},{"uid":"f89ddc46e74e6add","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/f89ddc46e74e6add","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb399a80e50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190994603,"stop":1673190994603,"duration":0}},{"uid":"e0402dc7fc9251b1","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/e0402dc7fc9251b1","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a12e4b110>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189385337,"stop":1673189385337,"duration":0}},{"uid":"8ec27fa16cd9c02f","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/8ec27fa16cd9c02f","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbaae49550>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187015813,"stop":1673187015813,"duration":0}}]},"816984eb1c783f0075e85d653c62f416":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"2df5669ea7085957","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/2df5669ea7085957","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa91369ca10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199984682,"stop":1673199984682,"duration":0}},{"uid":"ed49693b867ab5f5","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/ed49693b867ab5f5","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb39a38cf50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190991734,"stop":1673190991734,"duration":0}},{"uid":"3eda97fc35d3358c","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/3eda97fc35d3358c","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a1347cc50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189382481,"stop":1673189382481,"duration":0}},{"uid":"eb447f64dc36424f","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/eb447f64dc36424f","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbab519650>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187012694,"stop":1673187012694,"duration":0}}]},"0d1636b11e7dad598fdc84c6f66db4de":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"ecf9ce9430b1ea9a","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/ecf9ce9430b1ea9a","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa91369ca10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199982966,"stop":1673199982966,"duration":0}},{"uid":"6985a357a0e6d36e","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/6985a357a0e6d36e","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb39a38cf50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190990083,"stop":1673190990083,"duration":0}},{"uid":"48f0c3d84c930662","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/48f0c3d84c930662","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a1347cc50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189380853,"stop":1673189380853,"duration":0}},{"uid":"9146f33ea12e1f77","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/9146f33ea12e1f77","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbab519650>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187010902,"stop":1673187010902,"duration":0}}]},"6c6f11caf58a6be8840b57fae619464a":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"54895c518a8d905b","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/54895c518a8d905b","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa91369ca10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199981895,"stop":1673199981895,"duration":0}},{"uid":"90f66965b9537a64","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/90f66965b9537a64","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb39a38cf50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190989064,"stop":1673190989064,"duration":0}},{"uid":"fb12d85863f099c1","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/fb12d85863f099c1","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a1347cc50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189379840,"stop":1673189379840,"duration":0}},{"uid":"57209b32baa26363","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/57209b32baa26363","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbab519650>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187009826,"stop":1673187009826,"duration":0}}]},"00ce486fb67f877ddc901232a04d67c4":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"91b46f29a770ccd6","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/91b46f29a770ccd6","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa91369ca10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199983137,"stop":1673199983137,"duration":0}},{"uid":"69258443a228c297","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/69258443a228c297","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb39a38cf50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190990243,"stop":1673190990243,"duration":0}},{"uid":"2aa3ecd23e4b8449","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/2aa3ecd23e4b8449","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a1347cc50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189381008,"stop":1673189381008,"duration":0}},{"uid":"cba1f12257fd394f","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/cba1f12257fd394f","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbab519650>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187011083,"stop":1673187011083,"duration":0}}]},"6bb5a5fc132bd1e3a03b6cb58c193aa1":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"7ae8f10b89f0d709","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/7ae8f10b89f0d709","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa913578710>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199986201,"stop":1673199986201,"duration":0}},{"uid":"195884b02665a353","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/195884b02665a353","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb399a40cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190993213,"stop":1673190993213,"duration":0}},{"uid":"f82c3da0fa5ed66b","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/f82c3da0fa5ed66b","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a1323b890>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189383952,"stop":1673189383952,"duration":0}},{"uid":"54375e0383b96203","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/54375e0383b96203","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbab197590>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187014312,"stop":1673187014312,"duration":0}}]},"2e29daab58a0adf2ceb1093b8a9ed3fe":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"924559f14a618219","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/924559f14a618219","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa913262f90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199987001,"stop":1673199987001,"duration":0}},{"uid":"8d652d0682f4e631","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/8d652d0682f4e631","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb399aa80d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190993979,"stop":1673190993979,"duration":0}},{"uid":"a05a1a01342155e9","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/a05a1a01342155e9","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a132ef7d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189384715,"stop":1673189384715,"duration":0}},{"uid":"841c05031ddbab54","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/841c05031ddbab54","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbaae46f10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187015142,"stop":1673187015142,"duration":0}}]},"79a6432c68470a93d8e36a03d39540ca":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"2344c2af9bf3d849","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/2344c2af9bf3d849","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa912f51bd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199987516,"stop":1673199987516,"duration":0}},{"uid":"462b0df5d2a9a2c8","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/462b0df5d2a9a2c8","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb39a0ebf90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190994455,"stop":1673190994455,"duration":0}},{"uid":"63ca03bcd9500e0e","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/63ca03bcd9500e0e","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a12c31410>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189385191,"stop":1673189385191,"duration":0}},{"uid":"d18cc712c14f9f19","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/d18cc712c14f9f19","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbaac24a50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187015662,"stop":1673187015662,"duration":0}}]},"2ad9dc5bfa57ce90a1e4a728ecd6b77f":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"9048b4db3853b411","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/9048b4db3853b411","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa91369ca10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199982821,"stop":1673199982821,"duration":0}},{"uid":"c4bb43b2f6140f19","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/c4bb43b2f6140f19","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb39a38cf50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190989942,"stop":1673190989942,"duration":0}},{"uid":"738b68d10085a808","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/738b68d10085a808","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a1347cc50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189380714,"stop":1673189380714,"duration":0}},{"uid":"e9899e62c80935b0","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/e9899e62c80935b0","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbab519650>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187010756,"stop":1673187010756,"duration":0}}]},"482ff5173726feec3562b5fdaa64878c":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"81e551241d1dc317","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/81e551241d1dc317","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa91369ca10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199982363,"stop":1673199982363,"duration":0}},{"uid":"9542426e8a726f7b","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/9542426e8a726f7b","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb39a38cf50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190989505,"stop":1673190989505,"duration":0}},{"uid":"f287b59da87fcb5e","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/f287b59da87fcb5e","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a1347cc50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189380283,"stop":1673189380283,"duration":0}},{"uid":"c80b89427e16f617","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/c80b89427e16f617","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbab519650>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187010294,"stop":1673187010294,"duration":0}}]},"e930917e0c52a468075fd7086717a7c7":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"812d5f0bbd74e55a","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/812d5f0bbd74e55a","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa91369ca10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199983284,"stop":1673199983284,"duration":0}},{"uid":"fac104aac5c20dd8","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/fac104aac5c20dd8","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb39a38cf50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190990385,"stop":1673190990385,"duration":0}},{"uid":"14b8e9a2c2d9e247","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/14b8e9a2c2d9e247","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a1347cc50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189381147,"stop":1673189381147,"duration":0}},{"uid":"80a6a2e948e17444","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/80a6a2e948e17444","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbab519650>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187011231,"stop":1673187011231,"duration":0}}]},"7f03436489ba7c3eaca27dc156ea6587":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"942d94546c0dd4ca","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/942d94546c0dd4ca","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa912ffea10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199987337,"stop":1673199987337,"duration":0}},{"uid":"613f5c906cd7858e","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/613f5c906cd7858e","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb39a1f53d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190994288,"stop":1673190994288,"duration":0}},{"uid":"d0a01aeb2f7981bd","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/d0a01aeb2f7981bd","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a1324a2d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189385024,"stop":1673189385024,"duration":0}},{"uid":"4e4eb931745c4a1d","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/4e4eb931745c4a1d","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbaae0a6d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187015476,"stop":1673187015476,"duration":0}}]},"753028a2508affe184d15f1467f591c9":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"97a80a0d2248fd35","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/97a80a0d2248fd35","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa912ecc550>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199985145,"stop":1673199985145,"duration":0}},{"uid":"832d6092f5b5c40d","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/832d6092f5b5c40d","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb399b5c2d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190992180,"stop":1673190992180,"duration":0}},{"uid":"ebae6ff7c591017a","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/ebae6ff7c591017a","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a13152110>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189382926,"stop":1673189382926,"duration":0}},{"uid":"94f99acb832d22f5","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/94f99acb832d22f5","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbac4d0810>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187013185,"stop":1673187013186,"duration":1}}]},"b783c60386e99cb82424504d88d70d17":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"a1d2076ca295cd74","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/a1d2076ca295cd74","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa913570450>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199986374,"stop":1673199986374,"duration":0}},{"uid":"6b368b3b43082412","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/6b368b3b43082412","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb39a435b10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190993374,"stop":1673190993374,"duration":0}},{"uid":"4db21a11229fbb0a","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/4db21a11229fbb0a","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a13184dd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189384113,"stop":1673189384113,"duration":0}},{"uid":"56d3145664ce273d","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/56d3145664ce273d","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbab00cf90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187014490,"stop":1673187014490,"duration":0}}]},"de27e30bf159b80cb1d613ef51bd77ca":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"440cda88be9cee0b","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/440cda88be9cee0b","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa91369ca10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199984360,"stop":1673199984360,"duration":0}},{"uid":"ef8909287061bae9","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/ef8909287061bae9","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb39a38cf50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190991426,"stop":1673190991426,"duration":0}},{"uid":"c8a45e2fd8b5593","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/c8a45e2fd8b5593","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a1347cc50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189382178,"stop":1673189382178,"duration":0}},{"uid":"9ffd7499fb9c92d2","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/9ffd7499fb9c92d2","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbab519650>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187012361,"stop":1673187012361,"duration":0}}]},"9d7280034391d6dcde21ff9b783051ec":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"efc07525d58c9a22","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/efc07525d58c9a22","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa91369ca10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199981307,"stop":1673199981307,"duration":0}},{"uid":"99ab885c473a0fc0","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/99ab885c473a0fc0","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb39a38cf50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190988467,"stop":1673190988467,"duration":0}},{"uid":"5d54e8522fca6c2a","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/5d54e8522fca6c2a","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a1347cc50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189379246,"stop":1673189379246,"duration":0}},{"uid":"5d82b8ed97228eaf","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/5d82b8ed97228eaf","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbab519650>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187009187,"stop":1673187009187,"duration":0}}]},"df877e2aea48755134f5e042e9ce6ba8":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"fdf6f0764391a78c","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/fdf6f0764391a78c","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa91369ca10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199983738,"stop":1673199983738,"duration":0}},{"uid":"94238921e483f1c3","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/94238921e483f1c3","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb39a38cf50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190990826,"stop":1673190990826,"duration":0}},{"uid":"ff825b1e09aaa01a","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/ff825b1e09aaa01a","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a1347cc50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189381584,"stop":1673189381584,"duration":0}},{"uid":"9ae79e323773a9e8","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/9ae79e323773a9e8","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbab519650>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187011704,"stop":1673187011704,"duration":0}}]},"fe75c141123671b847c6180fcecf5abb":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"b572a455e69ff027","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/b572a455e69ff027","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa91304d050>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199986850,"stop":1673199986850,"duration":0}},{"uid":"fc27c6166a7d0244","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/fc27c6166a7d0244","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb399b15310>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190993833,"stop":1673190993833,"duration":0}},{"uid":"d6ff59c7df93eee","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/d6ff59c7df93eee","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a12c6e650>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189384569,"stop":1673189384569,"duration":0}},{"uid":"2d38d29907a7a7dd","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/2d38d29907a7a7dd","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbab24b950>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187014989,"stop":1673187014989,"duration":0}}]},"13abdb216ca159f4ae55817b65263ef2":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"d8df0adb49f49a98","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/d8df0adb49f49a98","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa9131f3390>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199986524,"stop":1673199986524,"duration":0}},{"uid":"d1ede01b6cfd3c07","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/d1ede01b6cfd3c07","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb399d5ce10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190993520,"stop":1673190993520,"duration":0}},{"uid":"f2b313d8e9e59cd8","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/f2b313d8e9e59cd8","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a1324d950>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189384260,"stop":1673189384260,"duration":0}},{"uid":"fd275f62539b13c0","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/fd275f62539b13c0","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbaae242d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187014645,"stop":1673187014645,"duration":0}}]},"68538b49d09f345c477432a374a3a804":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"7c3d17cfa1d97353","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/7c3d17cfa1d97353","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa91369ca10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199983905,"stop":1673199983905,"duration":0}},{"uid":"8ab6758e188a373c","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/8ab6758e188a373c","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb39a38cf50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190990986,"stop":1673190990986,"duration":0}},{"uid":"ea3d55a26b20d699","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/ea3d55a26b20d699","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a1347cc50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189381742,"stop":1673189381742,"duration":0}},{"uid":"d66ad3ce08e389e3","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/d66ad3ce08e389e3","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbab519650>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187011886,"stop":1673187011886,"duration":0}}]},"0f304db34f6536146077677251a5dd9d":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"fc1c29c9437a2e2d","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/fc1c29c9437a2e2d","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa91369ca10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199981750,"stop":1673199981750,"duration":0}},{"uid":"a3c4bdb820a4a7a2","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/a3c4bdb820a4a7a2","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb39a38cf50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190988905,"stop":1673190988905,"duration":0}},{"uid":"a41b20e3e00c2430","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/a41b20e3e00c2430","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a1347cc50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189379681,"stop":1673189379681,"duration":0}},{"uid":"c6202c14b7d1e26e","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/c6202c14b7d1e26e","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbab519650>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187009651,"stop":1673187009651,"duration":0}}]},"bc85bd397ffbeda4f13b89f5d5d89c73":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"b56fd08b9e2bbc7f","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/b56fd08b9e2bbc7f","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa91369ca10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199981609,"stop":1673199981609,"duration":0}},{"uid":"1e476f3af75714fc","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/1e476f3af75714fc","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb39a38cf50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190988764,"stop":1673190988764,"duration":0}},{"uid":"864216336c1c4e98","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/864216336c1c4e98","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a1347cc50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189379541,"stop":1673189379541,"duration":0}},{"uid":"b63150a3e30ecdec","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/b63150a3e30ecdec","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbab519650>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187009505,"stop":1673187009505,"duration":0}}]},"0a15a95601a73d747e3f71baae4f744c":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"20c1ee210924cc3c","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/20c1ee210924cc3c","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa91369ca10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199981448,"stop":1673199981448,"duration":0}},{"uid":"81f592d577e92bae","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/81f592d577e92bae","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb39a38cf50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190988608,"stop":1673190988608,"duration":0}},{"uid":"d4ff3529e39309e8","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/d4ff3529e39309e8","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a1347cc50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189379387,"stop":1673189379387,"duration":0}},{"uid":"1c6a7e913045c937","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/1c6a7e913045c937","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbab519650>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187009335,"stop":1673187009335,"duration":0}}]},"8217a2fe0f4364823e0d2a5b43da08c5":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"d359a05d440b5ce1","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/d359a05d440b5ce1","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa91369ca10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199982053,"stop":1673199982053,"duration":0}},{"uid":"89a5c1dbdd0a6a40","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/89a5c1dbdd0a6a40","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb39a38cf50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190989206,"stop":1673190989206,"duration":0}},{"uid":"5bd4e714342349fd","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/5bd4e714342349fd","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a1347cc50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189379981,"stop":1673189379981,"duration":0}},{"uid":"e69f72139400fc69","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/e69f72139400fc69","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbab519650>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187009971,"stop":1673187009971,"duration":0}}]},"81cf492b7bbe17b3f8325255e11f89dc":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"cf7c81f78f994fcb","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/cf7c81f78f994fcb","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa912ecc550>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199985436,"stop":1673199985436,"duration":0}},{"uid":"fce60cf398eb8f7","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/fce60cf398eb8f7","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb399b5c2d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190992488,"stop":1673190992488,"duration":0}},{"uid":"708808aa99c61e6a","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/708808aa99c61e6a","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a13152110>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189383227,"stop":1673189383227,"duration":0}},{"uid":"e824f660d93d1687","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/e824f660d93d1687","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbac4d0810>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187013524,"stop":1673187013524,"duration":0}}]},"da4444556c9f6f22b43300d3e8254f71":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":4,"unknown":0,"total":4},"items":[{"uid":"a2dbeeb0c70cf251","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/a2dbeeb0c70cf251","status":"passed","time":{"start":1673199980902,"stop":1673199981083,"duration":181}},{"uid":"9b9cf6ae73274178","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/9b9cf6ae73274178","status":"passed","time":{"start":1673190987848,"stop":1673190988060,"duration":212}},{"uid":"625c10b9a4ee7d94","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/625c10b9a4ee7d94","status":"passed","time":{"start":1673189378672,"stop":1673189378820,"duration":148}},{"uid":"5f4d824f442ce9f9","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/5f4d824f442ce9f9","status":"passed","time":{"start":1673187008446,"stop":1673187008648,"duration":202}}]},"2fc1292b113a790861c80436fb13a641":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"1d451fcf82af1553","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/1d451fcf82af1553","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa912ecc550>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199985292,"stop":1673199985292,"duration":0}},{"uid":"729adcabcebdafe8","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/729adcabcebdafe8","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb399b5c2d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190992325,"stop":1673190992325,"duration":0}},{"uid":"b0be55d1f021a528","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/b0be55d1f021a528","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a13152110>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189383066,"stop":1673189383066,"duration":0}},{"uid":"31845f5c15749938","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/31845f5c15749938","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbac4d0810>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187013336,"stop":1673187013336,"duration":0}}]},"49b0491d2450f499804ee62d6901a0c9":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"185916fdf49eb31b","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/185916fdf49eb31b","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa912feb8d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199986700,"stop":1673199986700,"duration":0}},{"uid":"f75ce0d17720a9a1","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/f75ce0d17720a9a1","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb399ad1c90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190993686,"stop":1673190993686,"duration":0}},{"uid":"923bc9e0005115b8","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/923bc9e0005115b8","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a12e4b7d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189384424,"stop":1673189384424,"duration":0}},{"uid":"266ff9eabc59f660","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/266ff9eabc59f660","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbab3508d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187014835,"stop":1673187014835,"duration":0}}]},"eb45923660f570fcf55d4f30f1e716c2":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"b38d9df95120e0f4","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/b38d9df95120e0f4","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa91369ca10>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199981086,"stop":1673199981086,"duration":0}},{"uid":"2f106d155ee3d064","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/2f106d155ee3d064","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb39a38cf50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190988311,"stop":1673190988311,"duration":0}},{"uid":"c07f4775ea16cdd3","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/c07f4775ea16cdd3","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a1347cc50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189379024,"stop":1673189379024,"duration":0}},{"uid":"6401b821c1a7558e","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/6401b821c1a7558e","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbab519650>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187008985,"stop":1673187008985,"duration":0}}]},"a2eb1f5ebd8044c7e0efa438f6b1258b":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"30aea0ed75da1677","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/30aea0ed75da1677","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa91357b510>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199987995,"stop":1673199987995,"duration":0}},{"uid":"bb1267d70982e508","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/bb1267d70982e508","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb39a0bb950>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190994914,"stop":1673190994914,"duration":0}},{"uid":"ac62b0e43960fe45","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/ac62b0e43960fe45","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a12b79710>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189385644,"stop":1673189385644,"duration":0}},{"uid":"4ce683ac78bc03fd","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/4ce683ac78bc03fd","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbaaf29310>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187016150,"stop":1673187016150,"duration":0}}]},"bf96e753322758d87fc7d1224295c65a":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"9cf1399c8f7643b3","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/9cf1399c8f7643b3","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa912ecc550>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199985744,"stop":1673199985744,"duration":0}},{"uid":"e4223407a3fdbc0b","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/e4223407a3fdbc0b","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb399b5c2d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190992772,"stop":1673190992772,"duration":0}},{"uid":"d25682ecf827b67c","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/d25682ecf827b67c","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a13152110>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189383510,"stop":1673189383510,"duration":0}},{"uid":"ece12e8a224a9f95","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/ece12e8a224a9f95","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbac4d0810>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187013825,"stop":1673187013825,"duration":0}}]},"6ed5f61a95ca4c2c6766ed9cf9dfed58":{"statistic":{"failed":0,"broken":4,"skipped":0,"passed":0,"unknown":0,"total":4},"items":[{"uid":"c76c03b67fc2fa23","reportUrl":"https://uraniumcore238.github.io/discord/19//#testresult/c76c03b67fc2fa23","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa912ecc550>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673199984827,"stop":1673199984827,"duration":0}},{"uid":"47796529aa9bf47e","reportUrl":"https://uraniumcore238.github.io/discord/8//#testresult/47796529aa9bf47e","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb399b5c2d0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673190991876,"stop":1673190991876,"duration":0}},{"uid":"64b2dfb88933a39b","reportUrl":"https://uraniumcore238.github.io/discord/7//#testresult/64b2dfb88933a39b","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9a13152110>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673189382624,"stop":1673189382624,"duration":0}},{"uid":"66250e436383faca","reportUrl":"https://uraniumcore238.github.io/discord/4//#testresult/66250e436383faca","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcbac4d0810>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1673187012847,"stop":1673187012847,"duration":0}}]}}